---
title: "Data Preparation"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

```{r , include=FALSE}
library(tidyr)
library(dplyr)
library(tibble)
starve <- tibble(read.csv("data/starveAll.csv")) %>% select(-X)


```

# Phase 1



# Phase 2



okay immma be real withu

skkskskksk


```{r echo=FALSE} 
#print(arrange(starve, starve$dif), n=205)

difMinus <- starve %>% filter(dif < 0) %>% arrange(line)
difMinus
difPlus <- starve %>% filter(dif >= 30) %>% arrange(line)
difPlus


#print(arrange(starve, starve$avg), n=205)


avgMinus <- starve %>% filter(avg < 40) %>% arrange(line)
avgMinus
avgPlus <- starve %>% filter(avg > 70) %>% arrange(line)
avgPlus


dupeCheck <- rbind(difMinus, difPlus, avgMinus, avgPlus)
print(arrange(dupeCheck, dupeCheck$line), n=55)
#8 of them repeat between dif and avg


```





# Phase 3

Following analysis of trait difference by sex alone, I sought to compare groups of interest on SNP Difference




Data was taken from [this table]("/data/morgante_lab/data/dgrp/dgrp2_tgeno_filtered_meanimputed.txt") of SNP variations by line



#### Groups of Interest

Male > Female

Top 20 Mean

Top 20 Difference



