---
title: "BayesC + GO term Overlay"
output:
  workflowr::wflow_html:
    toc: true
    latex_engine: "xelatex"
    code_folding: "hide"
editor_options:
  chunk_output_type: console
---



```{r 0-setup}

library(dplyr)
library(data.table)
library(ggplot2)
library(cowplot)
library(qqman)
library(viridis)
library(scales)
library(tidyverse)
library(ggcorrplot)
library(melt)
library(reshape2)

#options
options(bitmapType = "cairo")
options(error = function() traceback(3))

#seed
set.seed(123)

#ggplot holder list
gg <- vector(mode='list', length=12)
```

the idea:
  
  take in data table from end of bayesGo pipeline

create plot using columns of choice

```{r 0-functions}
#plotmaker funciton----
ggMake <- function(data, sex, custom.title, custom.Xlab, custom.Ylab){
  plothole <- ggplot(data,aes(y=cor,x=term,color=rgo))+
    geom_point()+scale_color_viridis(begin = 0.1, end=0.9,discrete=TRUE) +
    theme_minimal() +
    labs(x=custom.Xlab,y=custom.Ylab, tag=sex, title=custom.title) +
    theme(axis.text.x = element_text(angle = -45, size=10),
          text=element_text(size=10),
          plot.tag = element_text(size=15))
  return(plothole)
}

rmaxMake <- function(data, sex, custom.title, custom.Xlab, custom.Ylab){
  plothole <- ggplot(data,aes(y=cor,x=term,color=rmax))+
    geom_point()+scale_color_viridis(begin = 0.1, end=0.9,discrete=TRUE) +
    theme_minimal() +
    labs(x=custom.Xlab,y=custom.Ylab, tag=sex, title=custom.title) +
    theme(axis.text.x = element_text(angle = -45, size=10),
          text=element_text(size=10),
          plot.tag = element_text(size=15))
  return(plothole)
}

```


```{r dataTidy warning=FALSE, eval=TRUE}
temp <- na.omit(readRDS('snake/data/sr/40_all/go/sexf/allData.Rds'))

facs <- matrix(as.factor(unlist(temp[,1:4])), ncol=4)
cors <- as.numeric(unlist(temp[,5]))

data <- data.table(facs, cors)
colnames(data) <- c('sex', 'rmax', 'rgo', 'term', 'cor')

dataM <- data[data$sex=='m',]
dataF <- data[data$sex=='f',]

gg[[1]] <- ggMake(dataF, 'F', 'Effect of Max R2 on Accuracy by GO Term', 'GO Term', 'Prediction Accuracy')
gg[[2]] <- ggMake(dataM, 'M', 'Effect of Max R2 on Accuracy by GO Term', 'GO Term', 'Prediction Accuracy')
gg[[3]] <- ggMake(data, 'A', 'Effect of Max R2 on Accuracy by GO Term', 'GO Term', 'Prediction Accuracy')
gg[[4]] <- rmaxMake(data, 'A', 'Effect of Max R2 on Accuracy by GO Term', 'GO Term', 'Prediction Accuracy')



#The data we have here is a few things. The idea behind this work was to analyze the effects of GO terms asa Bayesian prior. By using two separate priors, we aset the first one to efffects of the go terms and the second to the ffects of all non go terms. 


gg[[4]] <- rmaxMake(data, 'A', 'Effect of Max R2 on Accuracy by GO Term', 'GO Term', 'Prediction Accuracy')

#colnames(hold) <- c("method", "cor")
#hold$method <- factor(hold$method, levels=unique(hold$method))

#for when the first works for sure, copy paste to compare and see if it mattered at all
#ggplot(data,aes(y=cor,x=term,color=rgo))+

```


```{r plot-print-all warning=FALSE, eval=TRUE}

plot_grid(gg[[1]],gg[[2]], ncol=2)
plot_grid(gg[[3]], ncol=1)
plot_grid(gg[[4]], ncol=1)
          

```











