
Histogram of BayesC M/F



```{r cor-female, warning=FALSE}

allData <- readRDS("data/all_hist_data_f.Rds")
print(colMeans(allData))
data <- ggTidy(allData)
data$method <- factor(data$method, levels=unique(data$method))

if(game){
  gg[[1]] <- ggplot(data, aes(x=method, y=cor, fill=method)) +
    geom_violin(color = NA, width = 0.65) +
    geom_boxplot(color='#440154FF', width = 0.15) +
    theme_minimal() +
    stat_summary(fun=mean, color='#440154FF', geom='point', 
                 shape=18, size=3, show.legend=FALSE) +
    labs(x=NULL,y='Correlation',tag='F', title='All Female') +
    theme(legend.position='none',
          axis.text.x = element_text(angle = -45, size=10),
          text=element_text(size=10),
          plot.tag = element_text(size=15)) +
    scale_fill_viridis(begin = 0.4, end=0.9,discrete=TRUE)
}

srData <- readRDS("data/sr_hist_data_f.Rds")
data <- ggTidy(srData)
data$method <- factor(data$method, levels=unique(data$method))

if(game){
  gg[[3]] <- ggplot(data, aes(x=method, y=cor, fill=method)) +
    geom_violin(color = NA, width = 0.65) +
    geom_boxplot(color='#440154FF', width = 0.15) +
    theme_minimal() +
    stat_summary(fun=mean, color='#440154FF', geom='point', 
                 shape=18, size=3, show.legend=FALSE) +
    labs(x=NULL,y='Correlation',tag='F', title='Univariate Female') +
    theme(legend.position='none',
          axis.text.x = element_text(angle = -45, size=10),
          text=element_text(size=10),
          plot.tag = element_text(size=15)) +
    scale_fill_viridis(begin = 0.4, end=0.9,discrete=TRUE)
}


```

```{r cor-male, warning=FALSE}

allData <- readRDS("data/all_hist_data_m.Rds")
print(colMeans(allData))
data <- ggTidy(allData)
data$method <- factor(data$method, levels=unique(data$method))

if(game){
  gg[[2]] <- ggplot(data, aes(x=method, y=cor, fill=method)) +
    geom_violin(color = NA, width = 0.65) +
    geom_boxplot(color='#440154FF', width = 0.15) +
    theme_minimal() +
    stat_summary(fun=mean, color='#440154FF', geom='point', 
                 shape=18, size=3, show.legend=FALSE) +
    labs(x=NULL,y='Correlation',tag='M', title='All Male') +
    theme(legend.position='none',
          axis.text.x = element_text(angle = -45, size=10),
          text=element_text(size=10),
          plot.tag = element_text(size=15)) +
    scale_fill_viridis(begin = 0.4, end=0.9,discrete=TRUE)
}

srData <- readRDS("data/sr_hist_data_m.Rds")
data <- ggTidy(srData)
data$method <- factor(data$method, levels=unique(data$method))

if(game){
  gg[[4]] <- ggplot(data, aes(x=method, y=cor, fill=method)) +
    geom_violin(color = NA, width = 0.65) +
    geom_boxplot(color='#440154FF', width = 0.15) +
    theme_minimal() +
    stat_summary(fun=mean, color='#440154FF', geom='point', 
                 shape=18, size=3, show.legend=FALSE) +
    labs(x=NULL,y='Correlation',tag='M', title='Univariate Male') +
    theme(legend.position='none',
          axis.text.x = element_text(angle = -45, size=10),
          text=element_text(size=10),
          plot.tag = element_text(size=15)) +
    scale_fill_viridis(begin = 0.4, end=0.9,discrete=TRUE)
}

```


### Univariate Models

```{r plot-print-all, warning=FALSE, eval=TRUE}

plot_grid(gg[[1]], ncol=1)

plot_grid(gg[[2]], ncol=1)

```

Comparison shows that multivariate methods do not significantly improve the model accuracy. As such, we will focus on univariate methods moving forward.

Below are the univariate models alone.


```{r plot-print-univariate, warning=FALSE, eval=TRUE}

plot_grid(gg[[3]], ncol=1)

plot_grid(gg[[4]], ncol=1)

```



```{r wflow-magicforlater}
generate_rmd <- function(path, alias, dir) {
  path <- paste0(dir, '/', path)
  abs.path <- tools::file_path_as_absolute(paste0('../', path))
  cat(
    "---\n",
    yaml::as.yaml(rmarkdown::yaml_front_matter(abs.path)),
    "---\n\n",
    "**Source file\\:** ", path, "\n\n",
    "```{r child='", abs.path, "'}\n```",
    sep="",
    file=alias
  )
}

wflow_dir_build <- function(files=NULL, dir='notebooks', ...) {
  if (is.null(files)) {
    files <- list.files(paste0('../', dir), recursive=T, 
                        include.dirs=T, pattern="./*.(r|R)md")
  }
  else {
    for (file in files) {
      path <- paste0(dir, "/", file)
      if (!file.exists(paste0('../', path)))
        stop(paste0("File doesn't exist: ../", path))
    }
  }
  
  file_aliases <- gsub("/", "__", files)
  mapply(generate_rmd, files, file_aliases, dir=dir)
  workflowr::wflow_build(files=file_aliases, ...)
  invisible(file.remove(file_aliases))
}

```

