resources: [cpus=302, mem_mb=8000000,jobweight=275, solo=1]

cluster:
  mkdir -p snakelogs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name={rule}
    --output=snakelogs/{rule}/%j-{wildcards}-{rule}.out
    --time=96:00:00

default-resources:
# - partition='fm-bigmem-1,fm-bigmem-3,compute'
  - partition='fm-bigmem-1,fm-bigmem-3,fm-bigmem-4'
# - partition='compute'
  - mem_mb=6000
  - time_min=1440
  - runtime=1440
  - nodes=1
  - runtime="4h"

local-cores: 1
latency-wait: 30
#jobs: 35
keep-going: True
keep-incomplete: True
rerun-incomplete: False
printshellcmds: True
use-conda: True

