\---
title: "Data and Scripts"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

## R Scripts

#### Group comparisons

#### [Male >> Female](../code/line_difMinus.R)

#### [Female >> Male](../code/line_difPlus.R)

#### [Low Average](../code/line_avgMinus.R)

#### [High Average](../code/line_avgPlus.R)


### Data Curation

#### [SR Extraction](../code/starveDataPrep.R)

#### [Ingroup Preparation](../code/fourLinePrep.R)

#### [SNP Consolidation](../code/combineSNP.R)


## Raw Data

### Starting point

#### [Starvation Resistance by Line](../data/starve.csv)


### Groups of interest

#### [Male >> Female](../data/difMinus.txt)

#### [Female >> Male](../data/difPlus.txt)

#### [Low Average](../data/avgMinus.txt)

#### [High Average](../data/avgPlus.txt)


### Results for each group 

#### [Male >> Female](../data/difMinus-result.txt)

#### [Female >> Male](../data/difPlus-result.txt)

#### [Low Average](../data/avgMinus-result.txt)

#### [High Average](../data/avgPlus-result.txt)


### SNPs of interest

#### [snpList](../data/snpList.txt)









