---
title: "Data Preparation"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

```{r , include=FALSE}
library(tidyr)
library(dplyr)
library(data.table)
starve <- tibble(read.csv("data/starve.csv")) %>% select(-X)


```

# Phase 1



for each file, 







# Phase 2



```{r echo=FALSE} 
#print(arrange(starve, starve$dif), n=205)

difMinus <- starve %>% filter(dif < 0) %>% arrange(line) %>% select(line)
difMinus <- as.data.table(difMinus)
fwrite(difMinus, "./data/difMinus.txt")

difPlus <- starve %>% filter(dif >= 30) %>% arrange(line) %>% select(line)
difPlus <- as.data.table(difPlus)
fwrite(difPlus, "./data/difPlus.txt")

#print(arrange(starve, starve$avg), n=205)

avgMinus <- starve %>% filter(avg < 40) %>% arrange(line) %>% select(line)
avgMinus <- as.data.table(avgMinus)
fwrite(avgMinus, "./data/avgMinus.txt")

avgPlus <- starve %>% filter(dif >= 30) %>% arrange(line) %>% select(line)
avgPlus <- as.data.table(avgPlus)
fwrite(avgPlus, "./data/avgPlus.txt")

```


```{r inclde=FALSE}
#dupeCheck <- rbind(difMinus, difPlus, avgMinus, avgPlus)
#print(arrange(dupeCheck, dupeCheck$line), n=55)
#8 of them repeat between dif and avg
#broken with data.table format

```

# Phase 3

Following analysis of trait difference by sex alone, I sought to compare groups of interest on SNP Difference




Data was taken from [this table]("/data/morgante_lab/data/dgrp/dgrp2_tgeno_filtered_meanimputed.txt") of SNP variations by line



#### Groups of Interest

Male > Female

Top 20 Mean

Top 20 Difference



