---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

# Overview
+ [Summary of Univariate and Multivariate models](allHist.html)




# GO Enrichment
+ [Enrichment Comparison](enrich.html)

## Sparse Group LASSO
 + [Sparse](sparseComp.html)
 + [Final](parsely.html)

## BayesC
+ [BayesGO: Layering GO annotations with Bayesian methods](goPlots.html)
+ [BayesGO preliminary results](bigGO.html)
+ [GObayesC Report](goReport.html)

## TBLUP
+ [GO-TBLUP Report](blupUp.html)

## Method Comparisons
+ [BayesC R2 Optimization](goBayesCor.html)

# Methods
+ [BayesC](man-BayesC.html)
+ [LASSO](lasso-OP.html)

# Others
## Corelated traits 
+ [Top Correlated Traits](top3.html)
+ [Covariance](covCor.html)

## Prediction
+ [Method Comparison](methodComp.html)
+ [Female Multiple Regression and Prediction](predict.html)
+ [Male Multiple Regression and Prediction](rewrite.html)

## Multiple Regression
+ [Linear Regression Adjusted](linearReg.html)
+ [Multiple Regression](multiReg.html)
+ [Linear Regression](linReg.html)
+ [Multiple Comparisons](multiComp.html)

## Misc
+ [Principal Componenet Analysis](pca.html)
+ [Starvation Resistance](starve.html)
+ [All Meeting Summaries](recap.html)
