---
title: "Optimization"
output:
  workflowr::wflow_html:
    toc: true
    latex_engine: "xelatex"
    code_folding: "hide"
editor_options:
  chunk_output_type: console
---


```{r 0-setup, include=FALSE, warning=FALSE}
#regular
if(1){
  library(dplyr)
  library(data.table)
  library(ggplot2)
  library(cowplot)
  library(qqman)
  library(viridis)
  library(scales)
  library(tidyverse)
  library(ggcorrplot)
  
  #options
  options(bitmapType = "cairo")
  options(error = function() traceback(3))
  
  #seed
  set.seed(123)
  
  #ggplot holder list
  gg <- vector(mode='list', length=12)
  setwd('/data2/morgante_lab/nklimko/rep/dgrp-starve/')
}
```


```{r lasso-all, warning=FALSE}


f <- readRDS("snake/data/zigure/lassoF.Rds")
m <- readRDS("snake/data/zigure/lassoM.Rds")

data <- f

gg[[1]] <- ggplot(data, aes(x=nfolds, y=cor, fill=relax)) +
  geom_point() +
  geom_smooth(formula = y ~ x, method=lm) 

gg[[2]] <- ggplot(data, aes(x=nfolds, y=time, fill=relax)) +
  geom_point() +
  geom_smooth(formula = y ~ x, method=lm) 

gg[[3]] <- ggplot(data, aes(x=dfmax, y=cor)) +
  geom_point() +
  geom_smooth(formula = y ~ x, method=lm) 

gg[[4]] <- ggplot(data, aes(x=dfmax, y=time)) +
  geom_point() +
  geom_smooth(formula = y ~ x, method=lm) 

data <- m

gg[[5]] <- ggplot(data, aes(x=nfolds, y=cor, fill=relax)) +
  geom_point() +
  geom_smooth(formula = y ~ x, method=lm) 

gg[[6]] <- ggplot(data, aes(x=nfolds, y=time, fill=relax)) +
  geom_point() +
  geom_smooth(formula = y ~ x, method=lm) 

gg[[7]] <- ggplot(data, aes(x=dfmax, y=cor)) +
  geom_point() +
  geom_smooth(formula = y ~ x, method=lm) 

gg[[8]] <- ggplot(data, aes(x=dfmax, y=time)) +
  geom_point() +
  geom_smooth(formula = y ~ x, method=lm) 


```





### Female Fold number vs. Correlation and Time

- relax decreases correlation while increasing runtime


```{r lasso-f-nfolds, warning=FALSE, eval=TRUE}

plot_grid(gg[[1]],gg[[2]], ncol=2)

```

### dfMax

- No effect on correlation or runtime

```{r lasso-f-dfmax, warning=FALSE, eval=TRUE}

plot_grid(gg[[3]],gg[[4]], ncol=2)

```


### Male Fold number vs. Correlation and Time

- relax decreases correlation while increasing runtime

```{r lasso-m-nfolds, warning=FALSE, eval=TRUE}

plot_grid(gg[[5]],gg[[6]], ncol=2)

```

### dfMax

- No effect on correlation or runtime

```{r lasso-m-dfmax, warning=FALSE, eval=TRUE}

plot_grid(gg[[7]],gg[[8]], ncol=2)

```



### Lasso Data

```{r allData-lasso}

lassoFinal <- readRDS("snake/data/zigure/lassoFinal.Rds")

print(lassoFinal)

```



```{r bayesOp, warning=FALSE, eval=TRUE}


bayesFinal <- readRDS("snake/data/zigure/bayesFinal.Rds")

data <- bayesFinal

gg[[9]] <- ggplot(data, aes(x=R2, y=cor, fill=sex)) +
  geom_point() +
  geom_smooth(formula = y ~ x, method=lm) 


gg[[10]] <- ggplot(data, aes(x=R2, y=time, fill=sex)) +
  geom_point() +
  geom_smooth(formula = y ~ x, method=lm) 



```


### BayesC


```{r bayes-plots, warning=FALSE, eval=TRUE}

plot_grid(gg[[9]],gg[[10]], ncol=2)

print(bayesFinal)



```


### Random Forest Female/Male

```{r randomforest, warning=FALSE, eval=TRUE}


#0.364, 0.382 f m 

data <- readRDS("snake/data/zigure/rf.Rds")

title <- "Correlation"
tagChar <- '.'


gg[[11]] <- ggplot(data, aes(x=sex, y=cor, fill=sex)) +
           geom_violin(color = NA, width = 0.65) +
           geom_boxplot(color='#440154FF', width = 0.15) +
           theme_minimal() +
           stat_summary(fun=mean, color='#440154FF', geom='point', 
                        shape=18, size=3, show.legend=FALSE) +
           labs(x=NULL,y=title,tag=tagChar) +
           theme(legend.position='none',
                 axis.text.x = element_text(angle = -45, size=10),
                 text=element_text(size=10),
                 plot.tag = element_text(size=15)) +
           scale_fill_viridis(begin = 0.4, end=0.9,discrete=TRUE)


plot_grid(gg[[11]], ncol=1)


```



### Data Driven Female/Male

```{r randomforest2, warning=FALSE, eval=TRUE}


#0.364, 0.382 f m 

data <- readRDS("snake/data/zigure/dd.Rds")

title <- "Correlation"
tagChar <- '.'


gg[[12]] <- ggplot(data, aes(x=sex, y=cor, fill=sex)) +
           geom_violin(color = NA, width = 0.65) +
           geom_boxplot(color='#440154FF', width = 0.15) +
           theme_minimal() +
           stat_summary(fun=mean, color='#440154FF', geom='point', 
                        shape=18, size=3, show.legend=FALSE) +
           labs(x=NULL,y=title,tag=tagChar) +
           theme(legend.position='none',
                 axis.text.x = element_text(angle = -45, size=10),
                 text=element_text(size=10),
                 plot.tag = element_text(size=15)) +
           scale_fill_viridis(begin = 0.4, end=0.9,discrete=TRUE)


plot_grid(gg[[12]], ncol=1)


```











