---
title: "Iterative Comparison"
output:
  workflowr::wflow_html:
    toc: true
    latex_engine: "xelatex"
    code_folding: "hide"
editor_options:
  chunk_output_type: console
---


```{r 0-setup, include=FALSE, warning=FALSE}
#regular
library(dplyr)
library(data.table)
library(ggplot2)
library(cowplot)
library(qqman)
library(doParallel)
library(viridis)
library(scales)
library(tidyverse)

#options
options(bitmapType = "cairo")
options(error = function() traceback(3))

#seed
set.seed(123)

#loop count and data limit
iter <- 50
#ggplot holder list
gg <- vector(mode='list', length=12)
setwd('/data2/morgante_lab/nklimko/rep/dgrp-starve/')

```

The following methods are currently implemented:

- BayesC

- GBLUP

- MultiBayesC

- MultiGBLUP

- mr.mash

- MultiLASSO



```{r multitrait-female, warning=FALSE}

###FEMALE
#setwd('/data2/morgante_lab/nklimko/rep/dgrp-starve/')

bayesC <- readRDS("snake/data/20_cor/bayesC_f_starvation.Rds")
gblup <- readRDS("snake/data/20_cor/gblup_f_starvation.Rds")

multigblupData <- readRDS('snake/data/20_cor/multigblup_f_starvation.Rds')
temp <- unlist(multigblupData)
multigblup <- temp[seq(1, length(temp), by=4)]

multibayesCData <- readRDS('snake/data/20_cor/multibayesC_f_starvation.Rds')
temp <- unlist(multibayesCData)
multibayesC <- temp[seq(1, length(temp), by=4)]

mr.mashData <- readRDS('snake/data/20_cor/mr.mash_f_starvation.Rds')
temp <- unlist(mr.mashData)
mr.mash <- temp[seq(1, length(temp), by=4)]

mlassoData <- readRDS('snake/data/20_cor/mlasso_f_starvation.Rds')
temp <- unlist(mlassoData)
mlasso <- temp[seq(1, length(temp), by=4)]

topmbc <- unlist(readRDS('snake/data/20_cor/multibayesC_f_sr.top3.Rds'))
top_multibayesC <- topmbc[seq(1, length(topmbc), by=16)]

topblup <- unlist(readRDS('snake/data/20_cor/multiblup_f_sr.top3.Rds'))
top_multiblup <- topblup[seq(1, length(topblup), by=16)]

temp <- c(gblup, bayesC, multigblup, multibayesC, mr.mash, mlasso, top_multiblup, top_multibayesC)

label <- c(rep("gblup", iter), rep("bayesC", iter), rep("multigblup", iter), rep("multibayesC", iter), rep("mr.mash", iter), rep('mlasso', iter), rep('top_multiblup', iter), rep("top_multibayesC", iter))

data <- data.table(cor=as.numeric(temp), method=label)

gg[[1]] <- ggplot(data, aes(x=method, y=cor, fill=method)) +
  geom_violin(color = NA, width = 0.65) +
  geom_boxplot(color='#440154FF', width = 0.15) +
  theme_minimal() +
  stat_summary(fun=mean, color='#440154FF', geom='point', 
               shape=18, size=3, show.legend=FALSE) +
  labs(x=NULL,y='Correlation between True and Predicted Phenotype',tag='F') +
  theme(legend.position='none',
        axis.text.x = element_text(angle = -45, size=10),
        text=element_text(size=10),
        plot.tag = element_text(size=15)) +
  scale_fill_viridis(begin = 0.4, end=0.9,discrete=TRUE)


print(paste0(c('bayesC', 'gblup', 'multibayesC', 'multigblup', 'mr.mash', 'top_multibayesC', 'top_multiblup'),': ',c(mean(bayesC), mean(gblup), mean(multibayesC), mean(multigblup), mean(mr.mash), mean(top_multibayesC), mean(top_multiblup))))


```


```{r multitrait-male}

### MALE
#setwd('/data2/morgante_lab/nklimko/rep/dgrp-starve/')


bayesC <- readRDS("snake/data/20_cor/bayesC_m_starvation.Rds")
gblup <- readRDS("snake/data/20_cor/gblup_m_starvation.Rds")

multigblupData <- readRDS('snake/data/20_cor/multigblup_m_starvation.Rds')
temp <- unlist(multigblupData)
multigblup <- temp[seq(1, length(temp), by=4)]

multibayesCData <- readRDS('snake/data/20_cor/multibayesC_m_starvation.Rds')
temp <- unlist(multibayesCData)
multibayesC <- temp[seq(1, length(temp), by=4)]

mr.mashData <- readRDS('snake/data/20_cor/mr.mash_m_starvation.Rds')
temp <- unlist(mr.mashData)
mr.mash <- temp[seq(1, length(temp), by=4)]

mlassoData <- ('snake/data/20_cor/mlasso_m_starvation.Rds')
temp <- unlist(mlassoData)
mlasso <- temp[seq(1, length(temp), by=4)]

topmbc <- unlist(readRDS('snake/data/20_cor/multibayesC_f_sr.top3.Rds'))
top_multibayesC <- topmbc[seq(1, length(topmbc), by=16)]

topblup <- unlist(readRDS('snake/data/20_cor/multiblup_f_sr.top3.Rds'))
top_multiblup <- topblup[seq(1, length(topblup), by=16)]

temp <- c(gblup, bayesC, multigblup, multibayesC, mr.mash, mlasso, top_multiblup, top_multibayesC)

label <- c(rep("gblup", iter), rep("bayesC", iter), rep("multigblup", iter), rep("multibayesC", iter), rep("mr.mash", iter), rep('mlasso', iter), rep('top_multiblup', iter), rep("top_multibayesC", iter))

data <- data.table(cor=as.numeric(temp), method=label)

gg[[2]] <- ggplot(data, aes(x=method, y=cor, fill=method)) +
  geom_violin(color = NA, width = 0.65) +
  geom_boxplot(color='#440154FF', width = 0.15) +
  theme_minimal() +
  stat_summary(fun=mean, color='#440154FF', geom='point', 
               shape=18, size=3, show.legend=FALSE) +
  labs(x=NULL,y='Correlation between True and Predicted Phenotype',tag='M') +
  theme(legend.position='none',
        axis.text.x = element_text(angle = -45, size=10),
        text=element_text(size=10),
        plot.tag = element_text(size=15)) +
  scale_fill_viridis(begin = 0.4, end=0.9,discrete=TRUE)

print(paste0(c('bayesC', 'gblup', 'multibayesC', 'multigblup', 'mr.mash', 'top_multibayesC', 'top_multiblup'),': ',c(mean(bayesC), mean(gblup), mean(multibayesC), mean(multigblup), mean(mr.mash), mean(top_multibayesC), mean(top_multiblup))))


```

### Correlation Coefficient Boxplots


```{r plot-print, warning=FALSE}

plot_grid(gg[[1]],gg[[2]], ncol=2)

```



### Alpha variation

```{r lasso-female-male}

setwd('snake/data/20_cor/')


tempDat <- list.files(pattern="lasso_\\d") %>% map(readRDS) %>% bind_cols()
#tempDat <- list.files(path='snake/data/20_cor', pattern="lasso_\\d") %>% map(readRDS) %>% bind_cols()

dat <- data.frame(cor=unlist(tempDat[,seq(1,9,2)]))
label = rep(seq(0,1,0.25), each=iter)

data <- data.table(cor=as.numeric(unlist(dat)), alpha=as.factor(label))


gg[[3]] <- ggplot(data, aes(x=alpha, y=cor, fill=alpha)) +
  geom_violin(color = NA, width = 0.65) +
  geom_boxplot(color='#440154FF', width = 0.15) +
  theme_minimal() +
  stat_summary(fun=mean, color='#440154FF', geom='point', 
               shape=18, size=3, show.legend=FALSE) +
  labs(x=NULL,y='Correlation between True and Predicted Phenotype',tag='F') +
  theme(legend.position='none',
        axis.text.x = element_text(angle = -45, size=10),
        text=element_text(size=10),
        plot.tag = element_text(size=15)) +
        scale_fill_viridis(begin = 0.4, end=0.9,discrete=TRUE)


dat <- data.frame(cor=unlist(tempDat[,seq(2,10,2)]))
label = rep(seq(0,1,0.25), each=iter)

data <- data.table(cor=as.numeric(unlist(dat)), alpha=as.factor(label))

gg[[4]] <- ggplot(data, aes(x=alpha, y=cor, fill=alpha)) +
  geom_violin(color = NA, width = 0.65) +
  geom_boxplot(color='#440154FF', width = 0.15) +
  theme_minimal() +
  stat_summary(fun=mean, color='#440154FF', geom='point', 
               shape=18, size=3, show.legend=FALSE) +
  labs(x=NULL,y='Correlation between True and Predicted Phenotype',tag='M') +
  theme(legend.position='none',
        axis.text.x = element_text(angle = -45, size=10),
        text=element_text(size=10),
        plot.tag = element_text(size=15)) +
        scale_fill_viridis(begin = 0.4, end=0.9,discrete=TRUE)


```



```{r runtime-print, warning=FALSE}


plot_grid(gg[[3]],gg[[4]], ncol=2)



```






